M48
; DRILL file {KiCad 9.0.1} date 2025-10-12T21:16:11-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-10-12T21:16:11-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0228
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0390
%
G90
G05
T2
X1.376Y-3.8051
T3
X1.8491Y-2.4071
X1.8891Y-2.2071
X1.9291Y-2.4071
T1
G00X1.663Y-3.8051
M15
G01X1.6795Y-3.8051
M16
G05
M30
